import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Admin painel',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <h2>Painel ADMIN</h2>
      {children}
    </>
  )
}
